### ISSUE TITLE
"name" Instead of "title" Field in Interaction Affordances

### ISSUE THREAD

**Issue by JKRhb** [roman-kravtsov/sdf-object-converter#1]
First of all, thank you for providing this very useful converter from SDF to WoT Thing Models! 

When using it for converting SDF object definitions, I noticed a small mislabeling: At the moment, the "label" field of affordances is translated to a "name" field. This should, however, be named "title" (see [here](https://w3c.github.io/wot-thing-description/#interactionaffordance)).

**Comment by roman-kravtsov** [comment]
Thank you for the feedback, any further feedback would be highly appreciated.

This issue has been closed by https://github.com/roman-kravtsov/sdf-object-converter/commit/4f6337068b56cd499e767665924a89bb7b28233e
