### ISSUE TITLE
"required" not Modelled as Array

### ISSUE THREAD

**Issue by JKRhb** [roman-kravtsov/sdf-object-converter#2]
At the moment, required affordances are labelled as such by inserting a boolean field in the affordance itself. According to the latest editor's draft, however, the keys of these affordances should be included in an array one level above (see [here](https://w3c.github.io/wot-thing-description/#td-model-required).

**Comment by roman-kravtsov** [comment]
Closed by https://github.com/roman-kravtsov/sdf-object-converter/commit/04efca9b0e4ab667c985829eee5e8c808b816aa7
