### ISSUE TITLE
@type is not set to "ThingModel" at the Thing Level

### ISSUE THREAD

**Issue by JKRhb** [roman-kravtsov/sdf-object-converter#3]
At the moment, the converter sets the `@type` of the resulting Thing Model to "Thing". This should, however, be "ThingModel" according to the latest editor's draft (see [here](https://w3c.github.io/wot-thing-description/#td-model-identification)).

**Comment by roman-kravtsov** [comment]
Closed by https://github.com/roman-kravtsov/sdf-object-converter/commit/2c329c87ad6dad76c041867df0b1752125c3f544
